### ISSUE TITLE
Commands silently fail on CentOS 7 (Linux)

### ISSUE THREAD

**Issue by rkubik** [huntertran/markdown-toc#14]
VSCode: 1.39.2
Auto Markdown TOC: 3.0.1

**Behaviour:**

After reloading vscode and disabling all other plugins I cannot get any commands from this plugin to work on CentOS 7. I can see the commands in the command-pane as well as in the right-click context menu but when executed the commands do nothing.

**Error log:**

```
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1521   ERR Error: [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1521   ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3390 Activating extension 'huntertran.auto-markdown-toc' failed: Cannot find module './ConfigManager'.
_logMessageInConsole @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3390
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:243 [Extension Host] Activating extension `huntertran.auto-markdown-toc` failed:  Cannot find module './ConfigManager'
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:243
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:243 [Extension Host] Here is the error stack:  Error: Cannot find module './ConfigManager'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
	at Function.Module._load (internal/modules/cjs/loader.js:510:25)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/home/russ/.vscode/extensions/huntertran.auto-markdown-toc-3.0.1/out/AutoMarkdownToc.js:4:25)
	at Object.<anonymous> (/home/russ/.vscode/extensions/huntertran.auto-markdown-toc-3.0.1/out/AutoMarkdownToc.js:264:3)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/home/russ/.vscode/extensions/huntertran.auto-markdown-toc-3.0.1/out/extension.js:4:27)
	at Object.<anonymous> (/home/russ/.vscode/extensions/huntertran.auto-markdown-toc-3.0.1/out/extension.js:26:3)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.s [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:32:963)
	at t.ExtHostExtensionService._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:755:484)
	at t.ExtHostExtensionService._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:300)
	at t.ExtHostExtensionService._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:665:360)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:296)
	at t.ExtensionsActivator._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:731)
	at n.length.Promise.all.r.map.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:409)
	at Array.map (<anonymous>)
	at t.ExtensionsActivator._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:397)
	at t.ExtensionsActivator.activateById (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:422)
	at t.ExtHostExtensionService._activateById (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:664:87)
	at t.ExtHostExtensionService.$activate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:672:442)
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2551 Error: command 'extension.updateMarkdownToc' not found
    at Proxy._tryExecuteCommand (/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3236)
    at r.then.i (/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3236)
onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2551
```

**Comment by huntertran** [comment]
does this bug happened to other plugins or just this one?

**Comment by rkubik** [comment]
Only this plugin.

**Comment by rkubik** [comment]
The latest CI build on master contains a similar error: https://travis-ci.org/huntertran/markdown-toc/builds/576540968

**Comment by huntertran** [comment]
I believe this bug was fixed in the latest version
